export const ANIMATION_STOPPED = "ANIMATION_STOPPED";
export const ANIMATION_STARTING = "ANIMATION_STARTING";
export const ANIMATION_SUCCEEDED = "ANIMATION_SUCCEEDED";
export const ANIMATION_UPDATED = "ANIMATION_UPDATED";
